package com.sportbetlive.sgdsn.util

data class Country(
    val isoCode: String,
    val name: String,
    val phoneCode: String,
    val languageCode: String,
    val flagEmoji: String
) {
    fun getDisplayName(): String = "$flagEmoji $name"
    fun getPhonePrefix(): String = phoneCode
}

object CountryData {
    
    val countries: List<Country> = listOf(
        Country("AF", "افغانستان", "+93", "fa", "🇦🇫"),
        Country("AL", "Shqipëria", "+355", "sq", "🇦🇱"),
        Country("DZ", "الجزائر", "+213", "ar", "🇩🇿"),
        Country("AD", "Andorra", "+376", "ca", "🇦🇩"),
        Country("AO", "Angola", "+244", "pt", "🇦🇴"),
        Country("AG", "Antigua and Barbuda", "+1268", "en", "🇦🇬"),
        Country("AR", "Argentina", "+54", "es", "🇦🇷"),
        Country("AM", "Հայաստdelays", "+374", "hy", "🇦🇲"),
        Country("AU", "Australia", "+61", "en", "🇦🇺"),
        Country("AT", "Österreich", "+43", "de", "🇦🇹"),
        Country("AZ", "Azərbaycan", "+994", "az", "🇦🇿"),
        Country("BS", "Bahamas", "+1242", "en", "🇧🇸"),
        Country("BH", "البحرين", "+973", "ar", "🇧🇭"),
        Country("BD", "বাংলাদেশ", "+880", "bn", "🇧🇩"),
        Country("BB", "Barbados", "+1246", "en", "🇧🇧"),
        Country("BY", "Беларусь", "+375", "be", "🇧🇾"),
        Country("BE", "België", "+32", "nl", "🇧🇪"),
        Country("BZ", "Belize", "+501", "en", "🇧🇿"),
        Country("BJ", "Bénin", "+229", "fr", "🇧🇯"),
        Country("BT", "འབྲུག", "+975", "dz", "🇧🇹"),
        Country("BO", "Bolivia", "+591", "es", "🇧🇴"),
        Country("BA", "Bosna i Hercegovina", "+387", "bs", "🇧🇦"),
        Country("BW", "Botswana", "+267", "en", "🇧🇼"),
        Country("BR", "Brasil", "+55", "pt", "🇧🇷"),
        Country("BN", "Brunei", "+673", "ms", "🇧🇳"),
        Country("BG", "България", "+359", "bg", "🇧🇬"),
        Country("BF", "Burkina Faso", "+226", "fr", "🇧🇫"),
        Country("BI", "Burundi", "+257", "fr", "🇧🇮"),
        Country("CV", "Cabo Verde", "+238", "pt", "🇨🇻"),
        Country("KH", "កម្ពុជា", "+855", "km", "🇰🇭"),
        Country("CM", "Cameroun", "+237", "fr", "🇨🇲"),
        Country("CA", "Canada", "+1", "en", "🇨🇦"),
        Country("CF", "Centrafrique", "+236", "fr", "🇨🇫"),
        Country("TD", "Tchad", "+235", "fr", "🇹🇩"),
        Country("CL", "Chile", "+56", "es", "🇨🇱"),
        Country("CN", "中国", "+86", "zh", "🇨🇳"),
        Country("CO", "Colombia", "+57", "es", "🇨🇴"),
        Country("KM", "Comores", "+269", "fr", "🇰🇲"),
        Country("CG", "Congo", "+242", "fr", "🇨🇬"),
        Country("CD", "RD Congo", "+243", "fr", "🇨🇩"),
        Country("CR", "Costa Rica", "+506", "es", "🇨🇷"),
        Country("CI", "Côte d'Ivoire", "+225", "fr", "🇨🇮"),
        Country("HR", "Hrvatska", "+385", "hr", "🇭🇷"),
        Country("CU", "Cuba", "+53", "es", "🇨🇺"),
        Country("CY", "Κύπρος", "+357", "el", "🇨🇾"),
        Country("CZ", "Česko", "+420", "cs", "🇨🇿"),
        Country("DK", "Danmark", "+45", "da", "🇩🇰"),
        Country("DJ", "Djibouti", "+253", "fr", "🇩🇯"),
        Country("DM", "Dominica", "+1767", "en", "🇩🇲"),
        Country("DO", "República Dominicana", "+1809", "es", "🇩🇴"),
        Country("EC", "Ecuador", "+593", "es", "🇪🇨"),
        Country("EG", "مصر", "+20", "ar", "🇪🇬"),
        Country("SV", "El Salvador", "+503", "es", "🇸🇻"),
        Country("GQ", "Guinea Ecuatorial", "+240", "es", "🇬🇶"),
        Country("ER", "ኤርትራ", "+291", "ti", "🇪🇷"),
        Country("EE", "Eesti", "+372", "et", "🇪🇪"),
        Country("SZ", "Eswatini", "+268", "en", "🇸🇿"),
        Country("ET", "ኢትዮጵያ", "+251", "am", "🇪🇹"),
        Country("FJ", "Fiji", "+679", "en", "🇫🇯"),
        Country("FI", "Suomi", "+358", "fi", "🇫🇮"),
        Country("FR", "France", "+33", "fr", "🇫🇷"),
        Country("GA", "Gabon", "+241", "fr", "🇬🇦"),
        Country("GM", "Gambia", "+220", "en", "🇬🇲"),
        Country("GE", "საქართველო", "+995", "ka", "🇬🇪"),
        Country("DE", "Deutschland", "+49", "de", "🇩🇪"),
        Country("GH", "Ghana", "+233", "en", "🇬🇭"),
        Country("GR", "Ελλάδα", "+30", "el", "🇬🇷"),
        Country("GD", "Grenada", "+1473", "en", "🇬🇩"),
        Country("GT", "Guatemala", "+502", "es", "🇬🇹"),
        Country("GN", "Guinée", "+224", "fr", "🇬🇳"),
        Country("GW", "Guiné-Bissau", "+245", "pt", "🇬🇼"),
        Country("GY", "Guyana", "+592", "en", "🇬🇾"),
        Country("HT", "Haïti", "+509", "fr", "🇭🇹"),
        Country("HN", "Honduras", "+504", "es", "🇭🇳"),
        Country("HK", "香港", "+852", "zh", "🇭🇰"),
        Country("HU", "Magyarország", "+36", "hu", "🇭🇺"),
        Country("IS", "Ísland", "+354", "is", "🇮🇸"),
        Country("IN", "भारत", "+91", "hi", "🇮🇳"),
        Country("ID", "Indonesia", "+62", "id", "🇮🇩"),
        Country("IR", "ایران", "+98", "fa", "🇮🇷"),
        Country("IQ", "العراق", "+964", "ar", "🇮🇶"),
        Country("IE", "Ireland", "+353", "en", "🇮🇪"),
        Country("IL", "ישראל", "+972", "he", "🇮🇱"),
        Country("IT", "Italia", "+39", "it", "🇮🇹"),
        Country("JM", "Jamaica", "+1876", "en", "🇯🇲"),
        Country("JP", "日本", "+81", "ja", "🇯🇵"),
        Country("JO", "الأردن", "+962", "ar", "🇯🇴"),
        Country("KZ", "Қазақстан", "+7", "kk", "🇰🇿"),
        Country("KE", "Kenya", "+254", "sw", "🇰🇪"),
        Country("KI", "Kiribati", "+686", "en", "🇰🇮"),
        Country("KP", "조선", "+850", "ko", "🇰🇵"),
        Country("KR", "대한민국", "+82", "ko", "🇰🇷"),
        Country("KW", "الكويت", "+965", "ar", "🇰🇼"),
        Country("KG", "Кыргызстан", "+996", "ky", "🇰🇬"),
        Country("LA", "ລາວ", "+856", "lo", "🇱🇦"),
        Country("LV", "Latvija", "+371", "lv", "🇱🇻"),
        Country("LB", "لبنان", "+961", "ar", "🇱🇧"),
        Country("LS", "Lesotho", "+266", "en", "🇱🇸"),
        Country("LR", "Liberia", "+231", "en", "🇱🇷"),
        Country("LY", "ليبيا", "+218", "ar", "🇱🇾"),
        Country("LI", "Liechtenstein", "+423", "de", "🇱🇮"),
        Country("LT", "Lietuva", "+370", "lt", "🇱🇹"),
        Country("LU", "Luxembourg", "+352", "fr", "🇱🇺"),
        Country("MO", "澳門", "+853", "zh", "🇲🇴"),
        Country("MG", "Madagasikara", "+261", "mg", "🇲🇬"),
        Country("MW", "Malawi", "+265", "en", "🇲🇼"),
        Country("MY", "Malaysia", "+60", "ms", "🇲🇾"),
        Country("MV", "ދިވެހިރާއްޖެ", "+960", "dv", "🇲🇻"),
        Country("ML", "Mali", "+223", "fr", "🇲🇱"),
        Country("MT", "Malta", "+356", "mt", "🇲🇹"),
        Country("MH", "Marshall Islands", "+692", "en", "🇲🇭"),
        Country("MR", "موريتانيا", "+222", "ar", "🇲🇷"),
        Country("MU", "Mauritius", "+230", "en", "🇲🇺"),
        Country("MX", "México", "+52", "es", "🇲🇽"),
        Country("FM", "Micronesia", "+691", "en", "🇫🇲"),
        Country("MD", "Moldova", "+373", "ro", "🇲🇩"),
        Country("MC", "Monaco", "+377", "fr", "🇲🇨"),
        Country("MN", "Монгол", "+976", "mn", "🇲🇳"),
        Country("ME", "Crna Gora", "+382", "sr", "🇲🇪"),
        Country("MA", "المغرب", "+212", "ar", "🇲🇦"),
        Country("MZ", "Moçambique", "+258", "pt", "🇲🇿"),
        Country("MM", "မြန်မာ", "+95", "my", "🇲🇲"),
        Country("NA", "Namibia", "+264", "en", "🇳🇦"),
        Country("NR", "Nauru", "+674", "en", "🇳🇷"),
        Country("NP", "नेपाल", "+977", "ne", "🇳🇵"),
        Country("NL", "Nederland", "+31", "nl", "🇳🇱"),
        Country("NZ", "New Zealand", "+64", "en", "🇳🇿"),
        Country("NI", "Nicaragua", "+505", "es", "🇳🇮"),
        Country("NE", "Niger", "+227", "fr", "🇳🇪"),
        Country("NG", "Nigeria", "+234", "en", "🇳🇬"),
        Country("MK", "Северна Македонија", "+389", "mk", "🇲🇰"),
        Country("NO", "Norge", "+47", "no", "🇳🇴"),
        Country("OM", "عُمان", "+968", "ar", "🇴🇲"),
        Country("PK", "پاکستان", "+92", "ur", "🇵🇰"),
        Country("PW", "Palau", "+680", "en", "🇵🇼"),
        Country("PS", "فلسطين", "+970", "ar", "🇵🇸"),
        Country("PA", "Panamá", "+507", "es", "🇵🇦"),
        Country("PG", "Papua New Guinea", "+675", "en", "🇵🇬"),
        Country("PY", "Paraguay", "+595", "es", "🇵🇾"),
        Country("PE", "Perú", "+51", "es", "🇵🇪"),
        Country("PH", "Pilipinas", "+63", "fil", "🇵🇭"),
        Country("PL", "Polska", "+48", "pl", "🇵🇱"),
        Country("PT", "Portugal", "+351", "pt", "🇵🇹"),
        Country("QA", "قطر", "+974", "ar", "🇶🇦"),
        Country("RO", "România", "+40", "ro", "🇷🇴"),
        Country("RU", "Россия", "+7", "ru", "🇷🇺"),
        Country("RW", "Rwanda", "+250", "rw", "🇷🇼"),
        Country("KN", "Saint Kitts and Nevis", "+1869", "en", "🇰🇳"),
        Country("LC", "Saint Lucia", "+1758", "en", "🇱🇨"),
        Country("VC", "Saint Vincent", "+1784", "en", "🇻🇨"),
        Country("WS", "Samoa", "+685", "sm", "🇼🇸"),
        Country("SM", "San Marino", "+378", "it", "🇸🇲"),
        Country("ST", "São Tomé e Príncipe", "+239", "pt", "🇸🇹"),
        Country("SA", "السعودية", "+966", "ar", "🇸🇦"),
        Country("SN", "Sénégal", "+221", "fr", "🇸🇳"),
        Country("RS", "Србија", "+381", "sr", "🇷🇸"),
        Country("SC", "Seychelles", "+248", "en", "🇸🇨"),
        Country("SL", "Sierra Leone", "+232", "en", "🇸🇱"),
        Country("SG", "Singapore", "+65", "en", "🇸🇬"),
        Country("SK", "Slovensko", "+421", "sk", "🇸🇰"),
        Country("SI", "Slovenija", "+386", "sl", "🇸🇮"),
        Country("SB", "Solomon Islands", "+677", "en", "🇸🇧"),
        Country("SO", "Soomaaliya", "+252", "so", "🇸🇴"),
        Country("ZA", "South Africa", "+27", "en", "🇿🇦"),
        Country("SS", "South Sudan", "+211", "en", "🇸🇸"),
        Country("ES", "España", "+34", "es", "🇪🇸"),
        Country("LK", "ශ්‍රී ලංකාව", "+94", "si", "🇱🇰"),
        Country("SD", "السودان", "+249", "ar", "🇸🇩"),
        Country("SR", "Suriname", "+597", "nl", "🇸🇷"),
        Country("SE", "Sverige", "+46", "sv", "🇸🇪"),
        Country("CH", "Schweiz", "+41", "de", "🇨🇭"),
        Country("SY", "سوريا", "+963", "ar", "🇸🇾"),
        Country("TW", "台灣", "+886", "zh", "🇹🇼"),
        Country("TJ", "Тоҷикистон", "+992", "tg", "🇹🇯"),
        Country("TZ", "Tanzania", "+255", "sw", "🇹🇿"),
        Country("TH", "ประเทศไทย", "+66", "th", "🇹🇭"),
        Country("TL", "Timor-Leste", "+670", "pt", "🇹🇱"),
        Country("TG", "Togo", "+228", "fr", "🇹🇬"),
        Country("TO", "Tonga", "+676", "to", "🇹🇴"),
        Country("TT", "Trinidad and Tobago", "+1868", "en", "🇹🇹"),
        Country("TN", "تونس", "+216", "ar", "🇹🇳"),
        Country("TR", "Türkiye", "+90", "tr", "🇹🇷"),
        Country("TM", "Türkmenistan", "+993", "tk", "🇹🇲"),
        Country("TV", "Tuvalu", "+688", "en", "🇹🇻"),
        Country("UG", "Uganda", "+256", "en", "🇺🇬"),
        Country("UA", "Україна", "+380", "uk", "🇺🇦"),
        Country("AE", "الإمارات", "+971", "ar", "🇦🇪"),
        Country("GB", "United Kingdom", "+44", "en", "🇬🇧"),
        Country("US", "United States", "+1", "en", "🇺🇸"),
        Country("UY", "Uruguay", "+598", "es", "🇺🇾"),
        Country("UZ", "Oʻzbekiston", "+998", "uz", "🇺🇿"),
        Country("VU", "Vanuatu", "+678", "bi", "🇻🇺"),
        Country("VA", "Vaticano", "+39", "it", "🇻🇦"),
        Country("VE", "Venezuela", "+58", "es", "🇻🇪"),
        Country("VN", "Việt Nam", "+84", "vi", "🇻🇳"),
        Country("YE", "اليمن", "+967", "ar", "🇾🇪"),
        Country("ZM", "Zambia", "+260", "en", "🇿🇲"),
        Country("ZW", "Zimbabwe", "+263", "en", "🇿🇼"),
        Country("PR", "Puerto Rico", "+1787", "es", "🇵🇷"),
        Country("GU", "Guam", "+1671", "en", "🇬🇺"),
        Country("VI", "US Virgin Islands", "+1340", "en", "🇻🇮"),
        Country("AS", "American Samoa", "+1684", "en", "🇦🇸"),
        Country("AW", "Aruba", "+297", "nl", "🇦🇼"),
        Country("BM", "Bermuda", "+1441", "en", "🇧🇲"),
        Country("KY", "Cayman Islands", "+1345", "en", "🇰🇾"),
        Country("CW", "Curaçao", "+599", "nl", "🇨🇼"),
        Country("FO", "Føroyar", "+298", "fo", "🇫🇴"),
        Country("GI", "Gibraltar", "+350", "en", "🇬🇮"),
        Country("GL", "Kalaallit Nunaat", "+299", "kl", "🇬🇱"),
        Country("GP", "Guadeloupe", "+590", "fr", "🇬🇵"),
        Country("MQ", "Martinique", "+596", "fr", "🇲🇶"),
        Country("NC", "Nouvelle-Calédonie", "+687", "fr", "🇳🇨"),
        Country("PF", "Polynésie française", "+689", "fr", "🇵🇫"),
        Country("RE", "La Réunion", "+262", "fr", "🇷🇪"),
        Country("SX", "Sint Maarten", "+1721", "nl", "🇸🇽"),
        Country("TC", "Turks and Caicos", "+1649", "en", "🇹🇨"),
        Country("VG", "British Virgin Islands", "+1284", "en", "🇻🇬"),
        Country("AI", "Anguilla", "+1264", "en", "🇦🇮"),
        Country("MS", "Montserrat", "+1664", "en", "🇲🇸"),
        Country("SH", "Saint Helena", "+290", "en", "🇸🇭"),
        Country("PM", "Saint-Pierre-et-Miquelon", "+508", "fr", "🇵🇲"),
        Country("WF", "Wallis-et-Futuna", "+681", "fr", "🇼🇫"),
        Country("YT", "Mayotte", "+262", "fr", "🇾🇹"),
        Country("GF", "Guyane française", "+594", "fr", "🇬🇫"),
        Country("BL", "Saint-Barthélemy", "+590", "fr", "🇧🇱"),
        Country("MF", "Saint-Martin", "+590", "fr", "🇲🇫"),
        Country("IM", "Isle of Man", "+44", "en", "🇮🇲"),
        Country("JE", "Jersey", "+44", "en", "🇯🇪"),
        Country("GG", "Guernsey", "+44", "en", "🇬🇬"),
        Country("AX", "Åland", "+358", "sv", "🇦🇽"),
        Country("CK", "Cook Islands", "+682", "en", "🇨🇰"),
        Country("NU", "Niue", "+683", "en", "🇳🇺"),
        Country("TK", "Tokelau", "+690", "en", "🇹🇰"),
        Country("NF", "Norfolk Island", "+672", "en", "🇳🇫"),
        Country("CX", "Christmas Island", "+61", "en", "🇨🇽"),
        Country("CC", "Cocos Islands", "+61", "en", "🇨🇨"),
        Country("FK", "Falkland Islands", "+500", "en", "🇫🇰"),
        Country("GS", "South Georgia", "+500", "en", "🇬🇸"),
        Country("PN", "Pitcairn", "+64", "en", "🇵🇳"),
        Country("EH", "الصحراء الغربية", "+212", "ar", "🇪🇭"),
        Country("XK", "Kosovë", "+383", "sq", "🇽🇰")
    )

    fun getCountryByIsoCode(isoCode: String): Country? {
        return countries.find { it.isoCode.equals(isoCode, ignoreCase = true) }
    }

    fun getCountryByLanguageCode(languageCode: String): Country? {
        return countries.find { it.languageCode.equals(languageCode, ignoreCase = true) }
    }

    fun getCountriesByLanguageCode(languageCode: String): List<Country> {
        return countries.filter { it.languageCode.equals(languageCode, ignoreCase = true) }
    }

    fun searchCountries(query: String): List<Country> {
        if (query.isBlank()) return countries
        val lowerQuery = query.lowercase()
        return countries.filter {
            it.name.lowercase().contains(lowerQuery) ||
            it.isoCode.lowercase().contains(lowerQuery) ||
            it.phoneCode.contains(lowerQuery)
        }
    }
}
